### ISSUE TITLE
Summer-infolettres : parcours dédié 

### ISSUE THREAD

**Issue by chloemacabeo** [SocialGouv/recosante#103]
Pour les abonnés infolettre ayant fini le parcours de sensibilisation des 57 infolettres; on souhaite créer un parcours estival dédié. 

**CA :** 
- envoie le jeudi comme pour autre infolettre 
- uniquement les abonnés ayant souscrit à l'infolettre et ayant fini parcours global 
- reprendre les emails existants
- liste dans l'ordre, des infolettres à envoyer : 

  - [x] sècheresse | https://recosante.beta.gouv.fr/articles/quels-comportements-adopter-en-cas-de-secheresse/
  - [x] moustiques tigre | https://recosante.beta.gouv.fr/articles/comment-se-proteger-du-moustique-tigre/
  - [x] ambroisie | https://recosante.beta.gouv.fr/articles/pourquoi-faut-il-lutter-contre-l-ambroisie/
  - [x] fortes chaleurs enfants | https://recosante.beta.gouv.fr/articles/comment-proteger-votre-sante-et-celle-de-vos-enfants-en-cas-de-fortes-chaleurs/
  - [x] UV enfants | https://recosante.beta.gouv.fr/articles/les-rayons-uv-quels-effets-sur-la-sante-et-celle-de-vos-enfants/
  - [x] protections solaires | https://recosante.beta.gouv.fr/articles/comment-choisir-et-utiliser-un-produit-de-protection-solaire/
  - [x] tiques | https://recosante.beta.gouv.fr/articles/comment-eviter-les-morsures-de-tiques/
  - [x] fortes chaleurs | https://recosante.beta.gouv.fr/articles/comment-se-proteger-en-cas-de-vague-de-chaleur/
  - [x] punaises de lit | comment lutter contre les punaises de lit ?https://recosante.beta.gouv.fr/articles/comment-lutter-contre-les-punaises-de-lit/
  - [x] jardiner | https://recosante.beta.gouv.fr/articles/comment-jardiner-sans-polluer/
  - [x] eau de pluie | https://recosante.beta.gouv.fr/articles/comment-utiliser-l-eau-de-pluie/
  - [x] inondations | quels sont les bons reflexes ? https://recosante.beta.gouv.fr/articles/inondations-quels-sont-les-bons-reflexes/
  - [x] champignons | https://recosante.beta.gouv.fr/articles/cueillette-de-champignons-comment-prevenir-les-intoxications/

**Comment by arnaudambro** [comment]
De ce que j'ai compris, on renvoyait toutes les heures de 8h30 à 15h30
On faisait ça parce que tous les indicateurs n'étaient pas disponibles dès le premier envoi
On finissait avec un envoi forcé à 16h30, un peu tard

On constate dans Brevo (https://my.brevo.com/lists/index/id/5) que pour la journée d'hier par exemple
2023-06-26 16:31 - 22 Contacts
2023-06-26 15:32 - 18 Contacts
2023-06-26 14:32 - 19 Contacts
2023-06-26 13:32 - 48 Contacts
2023-06-26 12:31 - 47 Contacts
2023-06-26 11:31 - 441 Contacts
2023-06-26 10:32 - 27 Contacts
2023-06-26 09:32 - 19 Contacts
2023-06-26 08:32 - 4 273 Contacts

J'ai modifié pour

qu'on commence l'envoi plus tôt - à 5h30
qu'on termine plus tôt, à 11h30, heure où on a récupéré le max d'indicateurs

**Comment by chloemacabeo** [comment]
Mise en place d'un test via BREVO : 
- dupliquer le mail 46 > en le nommant 57 
- vérifier si user ayant finit le parcours des 56 NL ; reçoit l'email concerné le  jeudi (demain) 29/06
