### ISSUE TITLE
Fouiller l'utilisation des notifs web

### ISSUE THREAD

**Issue by chloemacabeo** [SocialGouv/recosante#115]
- qui a accepté
- qui a clické sur une
- qui a désactivé

**Comment by arnaudambro** [comment]
étape 1: ça fonctionne !
- Android: ça marche comme une notification Push, avec un texte genre "Paris, le 1er août" / "Air: bon, Pollens: moyen" etc., et un lien "Voir tous les indicateurs" en plus
- Chrome Mac: il faut que Chrome soit ouvert - l'icône est celle de Chrome, pas celle de Recosanté (mais je pense que c'est normal et que y'a pas le choix) - Chrome permet d'installer l'app Recosanté (!) (c'est une app Chrome en fait, pas une app qu'on peut retrouver dans son dossier Applications) et quand on clique sur la notification Chrome, ça ouvre l'app ou le site si on n'a pas l'app
- Safari Mac: pas besoin que Safari soit ouvert (!) et ça ouvre Safari quand on clique dessus
- Firefox Mac: comme Chrome
- Edge Mac: comme Chrome

**Comment by arnaudambro** [comment]
je reçois désormais tous les jours sur Chrome, mais Safari non - je refais un test on verra demain

**Comment by arnaudambro** [comment]
notif reçue - 
à tester ensuite: les notifs sur iOS quand le nouveau flow d'inscription à la newsletter sera sorti
