### ISSUE TITLE
Bug envoi du programme infolettre été 2023

### ISSUE THREAD

**Issue by chloemacabeo** [SocialGouv/recosante#204]
Investigation à mener suite au retour d'Agnès V (SPF) "elle a reçu la 1ere infolettre été mais pas les suivantes) 

--- En vu du point du 13/09 on aimerait savoir : 
- nbr de contacts dans la base 
- taux d'ouverture au global / par mail 
- taux de désinscription au global / par mail

**Comment by chloemacabeo** [comment]
![Image](https://github.com/SocialGouv/recosante/assets/127193123/90852ff3-8699-47d0-a577-e62027c40397)



![Image](https://github.com/SocialGouv/recosante/assets/127193123/7bef4996-5b4b-4dbc-87cf-bada8682d850)

**Comment by arnaudambro** [comment]
lié à https://github.com/SocialGouv/recosante/issues/103

**Comment by chloemacabeo** [comment]
Code Python modifié il y a 4 mois > si tu recevais un mail-indicateurs avant que tu reçoives un mail info-lettre = si tu reçois un mail recosanté auj alors tu en reçois pas un second dans la même journée 

désormais : on t'envoie l'infolettre même si tu as reçu un mail-indicateurs dans la journée
