### ISSUE TITLE
BUG : lien de modification de la commune dans email KO

### ISSUE THREAD

**Issue by chloemacabeo** [SocialGouv/recosante#212]
Lien non fonctionnel : https://4olr6.r.a.d.sendibm1.com/mk/cl/f/sh/WCPzyXJTZ7viMAss3zUHuZIcygRz7Nfm/Kk5pWPao2_PN 

![Image](https://github.com/SocialGouv/recosante/assets/127193123/11240f07-7131-4e5d-a8e7-cad77e3ac962)

**Comment by chloemacabeo** [comment]
Lien fonctionnel ; toop - merci ! cependant il y a un effet bizarre au chargement de la page / lack + mention que le lien est hors délai or j'ai pris le mail d'il y a 1 h et je pense que ce lien n'a pas vocation à s'expirer dans le temps 

 https://recosante.beta.gouv.fr/profil/?user=KDRyE228&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTU3OTgxOTguMTg2NTUsInVpZCI6IktEUnlFMjI4In0.QBMKZNqbZ8oyuNVYj77_Z70EMhWG2vfOB9v_bvHAgQY



cc @arnaudambro

**Comment by arnaudambro** [comment]
il est mis à 30 minutes pour le moment
je peux mettre 30 jours si tu veux, ou même un an, mais le retirer ça touche à trop de logique dans le code, c'est un peu relou...

**Comment by chloemacabeo** [comment]
Ok no problemo ; mettons 30 jours tb !
