### ISSUE TITLE
BUG : mauvaises recommandations affichées dans email

### ISSUE THREAD

**Issue by chloemacabeo** [SocialGouv/recosante#213]
- Sur ensemble des indicateurs on appelle les mêmes recommandations de 'alerte_pollution'

![Image](https://github.com/SocialGouv/recosante/assets/127193123/0a5e7e58-1790-407c-b114-116a923d4ba9)

![Image](https://github.com/SocialGouv/recosante/assets/127193123/1caaf3a6-089e-4f56-ae55-e4b0ea9d54c6)

**Comment by arnaudambro** [comment]
![Image](https://github.com/SocialGouv/recosante/assets/31724752/fed07e41-502f-48c1-bdd9-3f3a9ba56341)

**Comment by arnaudambro** [comment]
https://github.com/SocialGouv/recosante/blob/17e296a07ca8522ef094e0fa4074c35bf61aa71d/api/ecosante/newsletter/models/newsletter.py#L299C51-L302C19
