### ISSUE TITLE
BUG : revoir manière afficher les textes sur page de résultat MOBILE

### ISSUE THREAD

**Issue by chloemacabeo** [SocialGouv/recosante#214]
Optimiser l'affichage sur recommandations en format liste : 

![Image](https://github.com/SocialGouv/recosante/assets/127193123/0a372db5-d249-46e6-a9c1-74104d96a778)

Optimiser l'affichage pour users avec petits écrans / police écriture grande : 

![Image](https://github.com/SocialGouv/recosante/assets/127193123/f4606b29-e85f-4ad7-8aa0-984d679c2552)

![Image](https://github.com/SocialGouv/recosante/assets/127193123/5c892cf3-59d5-43d0-9122-d073397a985a)

![Image](https://github.com/SocialGouv/recosante/assets/127193123/9a09e1dd-8ef5-43c5-b0f6-0c8aa89a2bf9)

**Comment by arnaudambro** [comment]
- [x] dark mode: désactivé
- [x] mode colonne: en dessous des écrans de larger < 336px
