### ISSUE TITLE
[mercredi 19 juillet] Améliorations UX mobile

### ISSUE THREAD

**Issue by chloemacabeo** [SocialGouv/recosante#91]
Voir maquettes : https://www.figma.com/file/gxHNi1hXW27dxgc4kaP4NN/Recosant%C3%A9?type=design&node-id=5393-8646&mode=design&t=ezFE4zqCeeVZSZxx-0

Pages optimisées : 
- Page de résultat mobile / desktop 
- Home mobile / desktop

**Comment by chloemacabeo** [comment]
Attente validation avec intrapreneurs - réu prévue le 29/06

**Comment by arnaudambro** [comment]
Mobile + desktop
- [ ] Homepage: 1/2j
- [ ] Indicateurs: 2.5j
- [ ] Articles: 1/2j
- [ ] Recommandations: 1/2j

**Comment by arnaudambro** [comment]
https://recosante-feat-new-homepage-mobile-25ynzt3p.dev.fabrique.social.gouv.fr/

**Comment by chloemacabeo** [comment]
TESTS -- 

- Page de résultat DESKTOP / MOBILE : 
![Capture d’écran 2023-07-20 à 18 19 24](https://github.com/SocialGouv/recosante/assets/127193123/4b8899c2-8150-43d3-89b3-2fb6c0699b4c)
aucune données ne remontent sur la page >> j'imagine que ce n'est pas branché en version preprod- peut on faker quelque chose pour pouvoir valider ceci stp ? 
-- CTA sticky en mobile ok ! 
-- Modif moteur de recherche : 
--- choix date OK
--- choix ville mobile : sur maquette on a un stylo pour modif direct mais non reproduit sur version de test. Pas grave c'est fonctionnel tout de même. A creuser plus tard éventuellement

- Home DESKTOP / MOBILE 
-- Le bloc 1 "Découvrez comment agir pour votre santé .." 
> on parle ici de la lettre info or le parcours est le full complet > chloé : revoir wordings pour + de cohérence (v2 voir si intéressant d'avoir un bloc / parcours dédié pour infolettre) 
> il manque le catchmail + chloé : voir avec Osiris si on doit ajouter le texte présent dans le parcours d'inscription




@chloemacabeo faire un tour sur wordings
