### ISSUE TITLE
Optimisations module inscription

### ISSUE THREAD

**Issue by chloemacabeo** [SocialGouv/recosante#97]

**Comment by Elnmz** [comment]
@arnaudambro est-ce que tu as une estimation pour ce ticket ?

**Comment by chloemacabeo** [comment]
https://www.figma.com/file/gxHNi1hXW27dxgc4kaP4NN/Recosant%C3%A9?type=design&node-id=5351-5712&mode=design&t=YjCn2oKCBl3roADk-0

CF commentaires dans les maquettes : 
- Fusionner étapes Fréquence et média (attention il y a écrit vigilence c'est vigilAnce) ;) 
- Validation de l'inscription mail indicateurs et passer à l'étape suivante : inverser les boutons 


![Image](https://github.com/SocialGouv/recosante/assets/127193123/873c88db-b5ab-482e-986c-483f751401a6)

**Comment by chloemacabeo** [comment]
ATTENTION sur https://recosante-feat-frontend-refacto-1q22px0d.dev.fabrique.social.gouv.fr/ en mobile on a certains éléments cassés : (non travaillé pour le moment mais pour y faire attention en cours de dev) 


![Image](https://github.com/SocialGouv/recosante/assets/127193123/34d4a03b-d6f7-45d6-abb3-4aa9c8532030)
![Image](https://github.com/SocialGouv/recosante/assets/127193123/a0e332dd-ed91-4f74-8b72-c6c53ea13c42)
![Image](https://github.com/SocialGouv/recosante/assets/127193123/598e6984-c0c6-4958-9e52-9d65e06255cb)

**Comment by arnaudambro** [comment]
@arnaudambro : tester en PWA sur iOS

**Comment by chloemacabeo** [comment]
TESTS : https://recosante-feat-new-subscription-funnel-4hy5ryd0.dev.fabrique.social.gouv.fr/
